### ISSUE TITLE
LibreOffice can't open openSUSE-Template-2019.otp

### ISSUE THREAD

**Issue by kkaempf** [openSUSE/artwork#34] opened 2019-05-08 07:52 UTC
When trying to open openSUSE-Template-2019.otp with LibreOffice 6.2 (libreoffice-6.2.3.2-2.1.x86_64) on Tumbleweed 20190502, CPU load goes to 100% and Gnome reports the application as 'not responding'. I need to kill LibreOffice at this point.

**Comment by kkaempf** [comment] 2019-05-08 16:13
> I'm able to load it just fine on GNOME, does LO output any important stuff in logs?

Uhm, where would LO log ?

I'm just running
```
> soffice openSUSE-Template-2019.otp 
```
and LO opens an empty window. I see a 'progress bar' at the bottom 'loading' and then Gnome kicks in telling me that this application is not responding.

**Comment by tux93** [comment] 2019-05-08 20:22
> > soffice openSUSE-Template-2019.otp 

That works just fine here on TW 20190506

**Comment by vinzv** [comment] 2020-01-09 22:38
I just re-tried that and could not reproduce it. Let's close the issue.

**Closed** 2020-01-09 23:35 UTC
